#logging:
#  level:
#    #        tk.mybatis: DEBUG
#    com.yuncitys.smart.oss: DEBUG
#server:
#  port: 9992
#
#spring:
#  profiles:
#    active: dev
#  application:
#    name: smart-tool
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#    default-property-inclusion: non_null
#  redis:
#    database: 10
#    host: ${REDIS_HOST:localhost}
#    port: ${REDIS_PORT:6379}
#    password: ${REDIS_PASSWORD:smart.IOT@YUNCITYS52_redis}
#    pool:
#      max-active: 20
#  http:
#    multipart:
#      max-file-size: 10Mb
#      max-request-size: 10Mb
## 配置数据库
#mybatis:
#  mapper-locations: "classpath*:mapper/*.xml"
#
## 配置swagger
#swagger:
#  enabled: true
#  base-package: com.yuncitys.smart.oss
#  title: smart-tools
#  version: 1.0.0.SNAPSHOT
#  description: 工具类模块
#  contact:
#    name: admin
#
## 配置用户认证和服务认证信息
#auth:
#  serviceId: smart-auth
#  #  uri: http://localhost:9777
#  user:
#    token-header: Authorization
#    limit-expire: 1440 # 一天过去,单位分钟
#  client:
#    id: smart-tool
#    secret: 123456
#    token-header: client-token
#
#mapper:
#  mappers: com.yuncitys.smart.security.common.mapper.CommonMapper
#
## 具体看类:CloudStorageConfig
#oss:
#  type: 2 # 类型 1：七牛  2：阿里云  3：腾讯云
#  qiniuDomain: http://xxxxx
#  qiniuPrefix: xxx
#  qiniuAccessKey: xxxxx
#  qiniuSecretKey: xxxxx
#  qiniuBucketName: xxxx
#
#  aliyunDomain: http://parking.oss-cn-shenzhen.aliyuncs.com
#  aliyunPrefix: oss
#  aliyunEndPoint: http://oss-cn-shenzhen.aliyuncs.com
#  aliyunAccessKeyId: LTAI3OZEAx06INin
#  aliyunAccessKeySecret : 4SzfbebI24IuN1d3Lr8FlM7ReU3wXW
#  aliyunBucketName: parking
#
#search:
#  lucence:
#    path: ./lucence/file
