logging:
  level:
    #        tk.mybatis: DEBUG
    com.smart.iot.charge: DEBUG
server:
  port: 9998

spring:
  application:
    name: smart-charge-server
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  datasource:
    name: test
    url: jdbc:mysql://119.23.224.60:3306/itparking?useUnicode=true&characterEncoding=UTF8
    username: root
    password: Syg18664566931
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      filters: stat
      maxActive: 100
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  redis:
    database: 1
    host: localhost
    port: 6379
    password: smart.IOT@yunctiys1_redis
    pool:
      max-active: 50
  rabbitmq:
    host: ${RABBIT_MQ_HOST:119.23.224.60}
    port:  ${RABBIT_MQ_PORT:5672}
    username: huan
    password: Syg18664566931
  zipkin:
    enabled: true
  sleuth:
    sampler:
      percentage: 1

# 配置数据库
mybatis:
  mapper-locations: "classpath*:mapper/*.xml"

# 配置swagger
swagger:
  enabled: true
  base-package: com.smart.iot.charge
  title: smart-charge-server
  version: 1.0.0.SNAPSHOT
  description: 城市智能停车平台
  contact:
    name: admin
  # 鉴权策略ID，对应 SecurityReferences ID
  authorization:
    name: Authorization
    key-name: Authorization
    auth-regex: ^.*$
# 配置用户认证和服务认证信息
auth:
  serviceId: smart-auth
  user:
    token-header: Authorization
    limit-expire: 1440 # 一天过去,单位分钟
  client:
    id: smart-charge-server
    secret: 123456
    token-header: client-token

mapper:
  mappers: com.yuncitys.smart.security.common.mapper.CommonMapper
