logging:
    level:
#        tk.mybatis: DEBUG
        com.smart.iot.mqtt: DEBUG
server:
    port: 9996

spring:
    application:
        name: smart-mqtt
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    datasource:
        name: test
        url: jdbc:mysql://119.23.224.60:3306/ag_admin?useUnicode=true&characterEncoding=UTF8
        username: root
        password: Syg18664566931
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        druid:
            filters: stat
            maxActive: 20
            initialSize: 1
            maxWait: 60000
            minIdle: 1
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            validationQuery: select 'x'
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            poolPreparedStatements: true
            maxOpenPreparedStatements: 20
    redis:
        database: 1
        host: localhost
        port: 6379
        password: smart.IOT@yunctiys1_redis
        pool:
            max-active: 20

# 配置数据库
mybatis:
    mapper-locations: "classpath*:mapper/*.xml"

# 配置swagger
swagger:
    enabled: true
    base-package: com.smart.iot.mqtt
    title: smart-mqtt
    version: 1.0.0.SNAPSHOT
    description: mqtt
    contact:
        name: admin

# 配置用户认证和服务认证信息
auth:
  serviceId: smart-auth
  user:
    token-header: Authorization
    limit-expire: 1440 # 一天过去,单位分钟
  client:
    id: smart-mqtt
    secret: 123456
    token-header: client-token

mapper:
  mappers: com.yuncitys.smart.security.common.mapper.CommonMapper

#MQTT配置信息
mqtt:
    #MQTT-服务器连接地址，如果有多个，用逗号隔开，如：tcp://127.0.0.1:61613，tcp://192.168.2.133:61613
    host: tcp://localhost:1884
    clientinid: iot-client-pull-${random.value}
    clientoutid: iot-client-push-${random.value}
    #MQTT-默认的消息推送主题，实际可在调用接口时指定  iot/experTopic/#
    topic: iot/experTopic/GW_00000666_DATA/#
    #发布到APP的topic
    appTopic: iot/experTopic/app/
    qoslevel: 1
    #MQTT-用户名
    username: YUNCITYS_IOT_EXPER
    #MQTT-密码
    password: admin123456
    #10S
    timeout: 10000
    #20s
    keepalive: 20
